### ISSUE TITLE
Discuss pros / cons of branching at another time?

### ISSUE THREAD

**Issue by CraigFaunce-NOAA** [Openscapes/2022-noaa-afsc#11]
@jules32 Thanks so much for all of this.  I got a bit confused by the terminology 'pull request' when i created a branch here.  Is that pullilng into Main?  Im used to seeing 'Create Merge Request'.

**Comment by jmlondon** [comment]
@CraigFaunce-NOAA the TLDR is that they are the same thing.

> “. . . GitHub and Bitbucket choose the name “pull request” because the first manual action is to pull the feature branch. Tools such as GitLab and others choose the name “merge request” because the final action is to merge the feature branch.”

You can read more details and insight here: 
⚠️ [deep dive into nitty gritty details]
https://blog.mergify.com/pull-request-vs-merge-request-whats-the-difference/

**Comment by CraigFaunce-NOAA** [comment]
Wow, thats really fascinating - Thank you!
