### ISSUE TITLE
Integration with Monday.com?

### ISSUE THREAD

**Issue by CraigFaunce-NOAA** [Openscapes/2022-noaa-afsc#15]
@jmlondon et al., anyone use Monday.com?  Been using this personally and this [link](https://monday.com/product/) looked interesting.  Not sure if NOAA ok.

**Comment by jmlondon** [comment]
I don't know anyone at NOAA that uses Monday.com. My inclination is that Google Calendar + Github Issues/Projects would meet the same need (it not exactly, but in spirit)
