### ISSUE TITLE
Gift Ideas for CH

### ISSUE THREAD

**Issue by jesseflamb** [Openscapes/2022-noaa-afsc#6]
Ideas?

**Comment by AlisonDeary-NOAA** [comment]
@jesseflamb winning

**Comment by keliaaxler** [comment]
@jesseflamb thanks for setting this up!

**Comment by jules32** [comment]
Great idea!

**Comment by jesseflamb** [comment]
Thinking something like [this](https://www.amazon.com/Adult-Coloring-Book-Relieving-Designs/dp/1945710799/ref=asc_df_1945710799/?tag=hyprod-20&linkCode=df0&hvadid=312057344057&hvpos=&hvnetw=g&hvrand=10779846029836347183&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9033316&hvtargid=pla-435513244064&psc=1)

**Comment by AlisonDeary-NOAA** [comment]
Like it. I was also thinking caffeine free [teas](https://www.myteadrop.com/products/caffeine-free-tea-sampler-15-drops?variant=32636022325295&currency=USD&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&utm_source=google&utm_medium=cpc&utm_campaign=&utm_device=c&utm_keyword=&gclid=Cj0KCQiAuvOPBhDXARIsAKzLQ8FpWj7skVrpYNeONwLAYYOu_bUi3nkD1Z5EE82kaxhZLhKJTIiGotQaAgQ2EALw_wcB)

**Comment by larogers123** [comment]
Some nice markers to go with would be good too

**Comment by jesseflamb** [comment]
> 

Markers or colored pencils

**Comment by larogers123** [comment]
**I'm going to make a BOLD comment** and maybe something in *italics*

**Comment by jesseflamb** [comment]
Ali: I liked where that conversation was going and we should continue it on Tuesday

**Comment by jesseflamb** [comment]
@AlisonDeary-NOAA
